- pipeline.id: metrics
  path.config: "/usr/share/logstash/pipeline/metrics.conf"
- pipeline.id: monitoring-op-mbe
  path.config: "/usr/share/logstash/pipeline/monitoring-op-mbe.conf"
- pipeline.id: monitoring-op-savoye
  path.config: "/usr/share/logstash/pipeline/monitoring-op-savoye.conf"
